### PR TITLE
init_project, init_rubocop

### PR DESCRIPTION
**Pull request by hieungv**

### CODE REVIEW

**Comment by hieungv** [comment]
image

**Comment by hieungv** [comment]
ready

**Comment by yanghoxom** [comment]
update database.yml please

**Comment by hieungv** [comment]
ready

**Comment by hieungv** [comment]
ready

**Comment by hieungv** [comment]
ready

**Comment by hieungv** [comment]
image

**Comment by hieungv** [comment]
ready

**Pull request merged**
